config/routes.rb
Rails.application.routes.draw do
      require "sidekiq/web"
    authenticate :user, lambda { |u| u.admin } do
    mount Sidekiq::Web => '/sidekiq'
  end

  devise_for :users
  root to: 'pages#home'

  resources :acquirers do
  end

  resources :targets do
  end

  resources :ipos do
  end

  resources :deals do
    resources :posts
  end

  resources :stocks do
    resources :comments do
    end
  end

  resources :portfolios do
  end

  resources :documents do
  end

   resources :comments do
  end

  resources :stocks do
    resources :fundamentals
  end

  resources :stocks do
    resources :articles
  end
end

app/models/acquirer.rb
class Acquirer < ApplicationRecord
  include AlgoliaSearch
  has_many :deals
  has_many :rounds, :through => :deals
  has_one_attached :acquirer_logo
  validates :name, presence: true
  validates :sector, presence: true
  validates :url, presence: true

  # algoliasearch do
  # end

  private

  def load_algolia
    index = Algolia::Index.new('Acquirer')
    index.add_object(self)
    puts "Reindex done"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :stock
  validates :date, presence: true
  validates :stock_id, presence: true
  validates :title, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :stock
  validates :title, presence: true
  has_one_attached :press_release
  has_one_attached :presentation
end

app/models/deal.rb
class Deal < ApplicationRecord
  include AlgoliaSearch
  has_one_attached :pdf
  has_one_attached :press_release
  belongs_to :acquirer
  belongs_to :target
  validates :date, presence: true
  validates :payment_method, presence: true
  validates :valuation_multiple, presence: true
  validates :bump, default: false
  validates :deal_value, presence: true
  validates :deal_currency, presence: true
  validates :private, default: false
  has_many :rounds, dependent: :destroy
  has_many :posts, dependent: :destroy
  # after_save :load_algolia

  # algoliasearch do
  # end

  private

  def load_algolia
    index = Algolia::Index.new('Deal')
    index.add_object(self)
    puts "Reindex done"
  end
end

app/models/document.rb
class Document < ApplicationRecord
  has_one_attached :document_pdf
end

app/models/financialtimearticle.rb
class FinancialTimeArticle < ApplicationRecord
  belongs_to :stock
end

app/models/fundamental.rb
class Fundamental < ApplicationRecord
  belongs_to :stock
end

app/models/ipo.rb
class Ipo < ApplicationRecord
  has_one_attached :ipo_logo
  has_one_attached :pdf_prospectus
  validates :name, presence: true
  validates :sector, presence: true
end

app/models/morningstar.rb
class MorningStar < ApplicationRecord
    belongs_to :stock
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
  has_many :stocks
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :deal
  validates :date, presence: true
  validates :content, presence: true
end

app/models/round.rb
class Round < ApplicationRecord
  belongs_to :deal
  belongs_to :acquirer
end

app/models/stock.rb
class Stock < ApplicationRecord
  has_many :comments
  has_many :articles
  has_many :fundamentals
  validates :name, presence: true, uniqueness: true
  validates :identifier, presence: true, uniqueness: true
  before_save :uppercase_name
  acts_as_taggable_on :tags

  private

  def uppercase_name
    name.upcase!
    identifier.upcase!
  end
end

app/models/target.rb
class Target < ApplicationRecord
  include AlgoliaSearch
  has_one_attached :annual_report
  has_one_attached :target_logo
  has_many :deals
  validates :name, presence: true, uniqueness: true
  validates :sector, presence: true

  # algoliasearch do
  # end

  private

  def load_algolia
    index = Algolia::Index.new('Target')
    index.add_object(self)
    puts "Reindex done"
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }
  has_one_attached :photo
end

app/controllers/acquirers_controller.rb
class AcquirersController < ApplicationController
  def index
    @acquirers = Acquirer.all
  end

  def new
    @acquirer = Acquirer.new
  end

  def create
    @acquirer = Acquirer.new(acquirer_params)
    if @acquirer.save
      redirect_to deals_path
    else
      render :new
    end
  end

  def show
    @acquirer = Acquirer.find(params[:id])
  end

  def edit
    @acquirer = Acquirer.find(params[:id])
  end

  def update
    @acquirer = Acquirer.find(params[:id])
    if @acquirer.update(acquirer_params)
      redirect_to deals_path
    else
      render :edit
    end
  end

  private

  def acquirer_params
    params.require(:acquirer).permit(:name, :sector, :identifier, :url, :acquirer_logo)
  end
end

app/controllers/deals_controller.rb
class DealsController < ApplicationController
  def index
    @deals = Deal.all.order("date DESC")
    @acquirers = Acquirer.all
    @targets = Target.all
    @ipos = Ipo.all
  end

  def new
    @deal = Deal.new
  end

  def create
    @deal = Deal.new(deal_params)
    if @deal.save!
      redirect_to deals_path
    else
      render :new
    end
  end

  def show
    @deal = Deal.find(params[:id])
  end

  def edit
    @deal = Deal.find(params[:id])
  end

  def update
    @deal = Deal.find(params[:id])
    if @deal.update(deal_params)
      redirect_to deal_path(@deal)
    else
      render :edit
    end
  end

  def destroy
    @deal = Deal.find(params[:id])
    @deal.destroy
    redirect_to deals_path
  end

  private

  def deal_params
    params.require(:deal).permit(:date, :premium, :payment_method, :valuation_multiple, :acquirer_id, :target_id, :pdf, :press_release, :payment_method, :valuation_type, :deal_value, :deal_currency, :comments, :bump, :private, :rumors, :offer_price, :ratio_shares)
  end
end

app/controllers/ipos_controller.rb
class IposController < ApplicationController
  def index
    @ipos = Ipo.all
  end

  def new
    @ipo = Ipo.new
  end

  def create
    @ipo = Ipo.new(ipo_params)
    if @ipo.save!
      redirect_to ipos_path
    else
      render :new
    end
  end

  def show
    @ipo = Ipo.find(params[:id])
  end

  def edit
    @ipo = Ipo.find(params[:id])
  end

  def update
    @ipo = Ipo.find(params[:id])
    if @ipo.update(ipo_params)
      redirect_to ipos_path
    else
      render :edit
    end
  end

  def destroy
    @ipo = Ipo.find(params[:id])
    @ipo.destroy
    redirect_to ipos_path
  end

  private

  def ipo_params
    params.require(:ipo).permit(:date, :name, :sector, :lead_underwriter, :valuation, :ipo_logo, :pdf_prospectus)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @comments = Comment.all.order("date DESC")
    @dailyft = daily_articles
  end

  def daily_articles
    tab = Array.new
    Article.where("date = ?", Date.current).each  { |val| tab.push([val.title, val.url, stock_name(val.stock_id)]) }
    return tab
  end

  def stock_name(id)
    return Stock.find(id).name
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all.order("date ASC")
  end

  def new
    @deal = Deal.find(params[:deal_id])
    @post = Post.new
  end

  def show
    @post = Post.find(params[:id])
  end

  def create
    @deal = Deal.find(params[:deal_id])
    @post = Post.new(post_params)
    @post.deal = @deal
    if @post.save!
      redirect_to deal_path(@deal)
    else
      render :new
    end
  end

  def edit
    @deal = Deal.find(params[:deal_id])
    @post = Post.find(params[:id])
  end

  def update
    @deal = Deal.find(params[:deal_id])
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to deal_path(@deal)
    else
      render :edit
    end
  end

  def destroy
    @deal = Deal.find(params[:deal_id])
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to deal_path(@deal)
  end

  private

  def post_params
    params.require(:post).permit(:date, :category, :content, :deal_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/acquirers/edit.html.erb
<h1>Update an Acquirer</h1>

<div class="container">
  <%= simple_form_for @acquirer do |f| %>
    <%= f.input :name %>
    <%= f.input :sector, collection: ["Aerospace & Defense", "Airlines", "Banks", "Basic Resources","Construction","Energy","Financials","Food & Beverage", "Health", "Healthcare", "Industrials", "Media", "Mining", "Oil & Gas", "Pharmaceuticals","Property", "Retail","Retail & Consumer","Support Services","Technology", "Travel & Leisure"] %>
    <%= f.input :identifier %>
    <%= f.input :url %>
    <%= f.input :acquirer_logo, as: :file, input_html: { class: "btn btn-outline-primary" } %>
    <%= f.submit "Update", class: "btn btn-primary" %>
  <% end %>
  <%= link_to "Back to the Acquirer", acquirer_path(@acquirer), class: "btn btn-ghost" %>
</div>

app/views/acquirers/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.5),rgba(0,0,0,0.2)), url(https://res.cloudinary.com/dtw3qvpgg/image/upload/v1582197640/background2_yzohoi.jpg);">
  <div class="container">
    <div class="row">
        <input class="form-control search-bar" type="text" placeholder="Search" aria-label="Search" id="search">
      </div>
    </div>
  </div>
</div>

  <div class="container">
      <div class="row text-center">
          <div class="col-3 col-md-3">
            <p><%= link_to "New Deal", new_deal_path %></p>
          </div>
          <div class="col-3 col-md-3">
            <p><%= link_to "New Acquirer", new_acquirer_path %></p>
          </div>
          <div class="col-3 col-md-3">
            <p><%= link_to "New Target", new_target_path %></p>
          </div>
          <div class="col-3 col-md-3">
            <p><%= link_to "New IPO", new_ipo_path %></p>
          </div>
      </div>
  <div class="row text-center">
          <div class="col-3 col-md-3">
            <%= link_to "Deals", deals_path, class: "btn btn-ghost" %>
          </div>
          <div class="col-3 col-md-3">
            <%= link_to "Acquirers", acquirers_path, class: "btn btn-ghost" %>
          </div>
          <div class="col-3 col-md-3">
            <%= link_to "Targets", targets_path, class: "btn btn-ghost" %>
          </div>
          <div class="col-3 col-md-3">
            <%= link_to "IPOs", ipos_path, class: "btn btn-ghost" %>
          </div>
      </div>


        <div class="acquirers">
          <h1>ACQUIRERS</h1>
            <div class="cards">
              <% @acquirers.each do |acquirer| %>
                <div class="card-product">
                  <%= cl_image_tag acquirer.acquirer_logo.key, width: 200, height: 200, crop: :pad if acquirer.acquirer_logo.attached? %>
                  <div class="card-product-infos">
                    <h2><%= link_to acquirer.name, acquirer_path(acquirer) %></h2>
                    <p><%= acquirer.sector %></p><strong><%= link_to acquirer.url, acquirer.url %></strong></p>
                  </div>
                </div>
              <% end %>
            </div>
        </div>
        </div>
      </div>
  </div>

app/views/acquirers/new.html.erb
<h1>Create a new Acquirer</h1>

<div class="container">
  <%= simple_form_for @acquirer do |f| %>
    <%= f.input :name %>
    <%= f.input :sector, collection: ["Aerospace & Defense", "Airlines", "Banks", "Basic Resources","Construction","Energy","Financials","Food & Beverage", "Health", "Healthcare", "Industrials", "Media", "Mining", "Oil & Gas", "Pharmaceuticals","Property", "Retail","Retail & Consumer","Support Services","Technology", "Travel & Leisure"] %>
    <%= f.input :identifier %>
    <%= f.input :url %>
    <%= f.input :acquirer_logo, as: :file, input_html: { class: "btn btn-outline-primary" } %>
    <%= f.submit "Create", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/acquirers/show.html.erb
<div class="container">
  <%= link_to "Back to Deals", deals_path, class: "btn btn-ghost" %>
  <%= link_to "Modify", edit_acquirer_path(@acquirer), class: "btn btn-ghost" %>
  <div class="card-product">
    <%= cl_image_tag @acquirer.acquirer_logo.key, width: 150, height: 150, crop: :pad if @acquirer.acquirer_logo.attached? %>
    <div class="card-product-infos">
      <h2><%= @acquirer.name %></h2>
      <p><%= @acquirer.sector %> <strong><%= link_to @acquirer.url, @acquirer.url %></strong></p>
    </div>
  </div>

  <% if @acquirer.identifier.empty? %>
    </div>
    <% else %>
        <div class="card-product-infos justify-content-center">
          <% response = open("https://markets.ft.com/data/equities/tearsheet/profile?s=#{@acquirer.identifier}").read %>
          <% html_doc = Nokogiri::HTML(response) %>
          <% portfolio = [] %>
            <% html_doc.search('.mod-tearsheet-profile-section').each do |label| %>
              <p class="text-justify"><%= label = label.text.strip %></p>
            <% end %>
        </div>
      </div>
    <% end %>
</div>