config/routes.rb
Rails.application.routes.draw do
      require "sidekiq/web"
    authenticate :user, lambda { |u| u.admin } do
    mount Sidekiq::Web => '/sidekiq'
  end

  devise_for :users
  root to: 'pages#home'

  resources :acquirers do
  end

  resources :targets do
  end

  resources :ipos do
  end

  resources :deals do
    resources :posts
  end

  resources :stocks do
    resources :comments do
    end
  end

  resources :portfolios do
  end

  resources :documents do
  end

   resources :comments do
  end

  resources :stocks do
    resources :fundamentals
  end

  resources :stocks do
    resources :articles
  end
end

app/models/acquirer.rb
class Acquirer < ApplicationRecord
  include AlgoliaSearch
  has_many :deals
  has_many :rounds, :through => :deals
  has_one_attached :acquirer_logo
  validates :name, presence: true
  validates :sector, presence: true
  validates :url, presence: true

  # algoliasearch do
  # end

  private

  def load_algolia
    index = Algolia::Index.new('Acquirer')
    index.add_object(self)
    puts "Reindex done"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :stock
  validates :date, presence: true
  validates :stock_id, presence: true
  validates :title, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :stock
  validates :title, presence: true
  has_one_attached :press_release
  has_one_attached :presentation
end

app/models/deal.rb
class Deal < ApplicationRecord
  include AlgoliaSearch
  has_one_attached :pdf
  has_one_attached :press_release
  belongs_to :acquirer
  belongs_to :target
  validates :date, presence: true
  validates :payment_method, presence: true
  validates :valuation_multiple, presence: true
  validates :bump, default: false
  validates :deal_value, presence: true
  validates :deal_currency, presence: true
  validates :private, default: false
  has_many :rounds, dependent: :destroy
  has_many :posts, dependent: :destroy
  # after_save :load_algolia

  # algoliasearch do
  # end

  private

  def load_algolia
    index = Algolia::Index.new('Deal')
    index.add_object(self)
    puts "Reindex done"
  end
end

app/models/document.rb
class Document < ApplicationRecord
  has_one_attached :document_pdf
end

app/models/financialtimearticle.rb
class FinancialTimeArticle < ApplicationRecord
  belongs_to :stock
end

app/models/fundamental.rb
class Fundamental < ApplicationRecord
  belongs_to :stock
end

app/models/ipo.rb
class Ipo < ApplicationRecord
  has_one_attached :ipo_logo
  has_one_attached :pdf_prospectus
  validates :name, presence: true
  validates :sector, presence: true
end

app/models/morningstar.rb
class MorningStar < ApplicationRecord
    belongs_to :stock
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
  has_many :stocks
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :deal
  validates :date, presence: true
  validates :content, presence: true
end

app/models/round.rb
class Round < ApplicationRecord
  belongs_to :deal
  belongs_to :acquirer
end

app/models/stock.rb
class Stock < ApplicationRecord
  has_many :comments
  has_many :articles
  has_many :fundamentals
  validates :name, presence: true, uniqueness: true
  validates :identifier, presence: true, uniqueness: true
  before_save :uppercase_name
  acts_as_taggable_on :tags

  private

  def uppercase_name
    name.upcase!
    identifier.upcase!
  end
end

app/models/target.rb
class Target < ApplicationRecord
  include AlgoliaSearch
  has_one_attached :annual_report
  has_one_attached :target_logo
  has_many :deals
  validates :name, presence: true, uniqueness: true
  validates :sector, presence: true

  # algoliasearch do
  # end

  private

  def load_algolia
    index = Algolia::Index.new('Target')
    index.add_object(self)
    puts "Reindex done"
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }
  has_one_attached :photo
end

app/controllers/deals_controller.rb
class DealsController < ApplicationController
  def index
    @deals = Deal.all.order("date DESC")
    @acquirers = Acquirer.all
    @targets = Target.all
    @ipos = Ipo.all
  end

  def new
    @deal = Deal.new
  end

  def create
    @deal = Deal.new(deal_params)
    if @deal.save!
      redirect_to deals_path
    else
      render :new
    end
  end

  def show
    @deal = Deal.find(params[:id])
  end

  def edit
    @deal = Deal.find(params[:id])
  end

  def update
    @deal = Deal.find(params[:id])
    if @deal.update(deal_params)
      redirect_to deal_path(@deal)
    else
      render :edit
    end
  end

  def destroy
    @deal = Deal.find(params[:id])
    @deal.destroy
    redirect_to deals_path
  end

  private

  def deal_params
    params.require(:deal).permit(:date, :premium, :payment_method, :valuation_multiple, :acquirer_id, :target_id, :pdf, :press_release, :payment_method, :valuation_type, :deal_value, :deal_currency, :comments, :bump, :private, :rumors, :offer_price, :ratio_shares)
  end
end

app/controllers/ipos_controller.rb
class IposController < ApplicationController
  def index
    @ipos = Ipo.all
  end

  def new
    @ipo = Ipo.new
  end

  def create
    @ipo = Ipo.new(ipo_params)
    if @ipo.save!
      redirect_to ipos_path
    else
      render :new
    end
  end

  def show
    @ipo = Ipo.find(params[:id])
  end

  def edit
    @ipo = Ipo.find(params[:id])
  end

  def update
    @ipo = Ipo.find(params[:id])
    if @ipo.update(ipo_params)
      redirect_to ipos_path
    else
      render :edit
    end
  end

  def destroy
    @ipo = Ipo.find(params[:id])
    @ipo.destroy
    redirect_to ipos_path
  end

  private

  def ipo_params
    params.require(:ipo).permit(:date, :name, :sector, :lead_underwriter, :valuation, :ipo_logo, :pdf_prospectus)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @comments = Comment.all.order("date DESC")
    @dailyft = daily_articles
  end

  def daily_articles
    tab = Array.new
    Article.where("date = ?", Date.current).each  { |val| tab.push([val.title, val.url, stock_name(val.stock_id)]) }
    return tab
  end

  def stock_name(id)
    return Stock.find(id).name
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon topnavbar-design  d-flex justify-content-around">
  <%= link_to "https://www.boussard-gavaudan.com/", class: "navbar-brand" do %>
    <%= cl_image_tag "https://res.cloudinary.com/dtw3qvpgg/image/upload/v1588410420/logo_BG_oml90m.jpg", :class => "style-image-navbar" %>
  <% end %>

  <h2>Hi 👋 <%= current_user.first_name if user_signed_in? %>! </h2>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto navbar-design">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", root_path, class: "btn btn-primary ml-1 mr-1" %>
        </li>
        <li class="nav-item">
          <%= link_to "Messages", "#", class: "btn btn-primary ml-1 mr-1" %>
        </li>
        <li class="nav-item dropdown">
          <% if current_user.photo.attached?%>
            <%= cl_image_tag current_user.photo.key, width: 45, height: 45, crop: :thumb, radius: :max, face: :center, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                <%= link_to "Your Profile", edit_user_registration_path, class: "dropdown-item" %>
                <%= link_to "Your Documents", documents_path, class: "dropdown-item" %>
                <%= link_to "Log Out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
              </div>
          <% else %>
            <%= image_tag "default_user_image.png", alt: "Profile picture", width: 45, height: 45, crop: :thumb, radius: :max, face: :center, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                <%= link_to "Your Profile", edit_user_registration_path, class: "dropdown-item" %>
                <%= link_to "Your Documents", documents_path, class: "dropdown-item" %>
                <%= link_to "Log Out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
              </div>
          <% end %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>