config/routes.rb
Rails.application.routes.draw do
      require "sidekiq/web"
    authenticate :user, lambda { |u| u.admin } do
    mount Sidekiq::Web => '/sidekiq'
  end

  devise_for :users
  root to: 'pages#home'

  resources :acquirers do
  end

  resources :targets do
  end

  resources :ipos do
  end

  resources :deals do
    resources :posts
  end

  resources :stocks do
    resources :comments do
    end
  end

  resources :portfolios do
  end

  resources :documents do
  end

   resources :comments do
  end

  resources :stocks do
    resources :fundamentals
  end

  resources :stocks do
    resources :articles
  end
end

app/models/acquirer.rb
class Acquirer < ApplicationRecord
  include AlgoliaSearch
  has_many :deals
  has_many :rounds, :through => :deals
  has_one_attached :acquirer_logo
  validates :name, presence: true
  validates :sector, presence: true
  validates :url, presence: true

  # algoliasearch do
  # end

  private

  def load_algolia
    index = Algolia::Index.new('Acquirer')
    index.add_object(self)
    puts "Reindex done"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :stock
  validates :date, presence: true
  validates :stock_id, presence: true
  validates :title, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :stock
  validates :title, presence: true
  has_one_attached :press_release
  has_one_attached :presentation
end

app/models/deal.rb
class Deal < ApplicationRecord
  include AlgoliaSearch
  has_one_attached :pdf
  has_one_attached :press_release
  belongs_to :acquirer
  belongs_to :target
  validates :date, presence: true
  validates :payment_method, presence: true
  validates :valuation_multiple, presence: true
  validates :bump, default: false
  validates :deal_value, presence: true
  validates :deal_currency, presence: true
  validates :private, default: false
  has_many :rounds, dependent: :destroy
  has_many :posts, dependent: :destroy
  # after_save :load_algolia

  # algoliasearch do
  # end

  private

  def load_algolia
    index = Algolia::Index.new('Deal')
    index.add_object(self)
    puts "Reindex done"
  end
end

app/models/document.rb
class Document < ApplicationRecord
  has_one_attached :document_pdf
end

app/models/financialtimearticle.rb
class FinancialTimeArticle < ApplicationRecord
  belongs_to :stock
end

app/models/fundamental.rb
class Fundamental < ApplicationRecord
  belongs_to :stock
end

app/models/ipo.rb
class Ipo < ApplicationRecord
  has_one_attached :ipo_logo
  has_one_attached :pdf_prospectus
  validates :name, presence: true
  validates :sector, presence: true
end

app/models/morningstar.rb
class MorningStar < ApplicationRecord
    belongs_to :stock
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
  has_many :stocks
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :deal
  validates :date, presence: true
  validates :content, presence: true
end

app/models/round.rb
class Round < ApplicationRecord
  belongs_to :deal
  belongs_to :acquirer
end

app/models/stock.rb
class Stock < ApplicationRecord
  has_many :comments
  has_many :articles
  has_many :fundamentals
  validates :name, presence: true, uniqueness: true
  validates :identifier, presence: true, uniqueness: true
  before_save :uppercase_name
  acts_as_taggable_on :tags

  private

  def uppercase_name
    name.upcase!
    identifier.upcase!
  end
end

app/models/target.rb
class Target < ApplicationRecord
  include AlgoliaSearch
  has_one_attached :annual_report
  has_one_attached :target_logo
  has_many :deals
  validates :name, presence: true, uniqueness: true
  validates :sector, presence: true

  # algoliasearch do
  # end

  private

  def load_algolia
    index = Algolia::Index.new('Target')
    index.add_object(self)
    puts "Reindex done"
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }
  has_one_attached :photo
end

app/controllers/deals_controller.rb
class DealsController < ApplicationController
  def index
    @deals = Deal.all.order("date DESC")
    @acquirers = Acquirer.all
    @targets = Target.all
    @ipos = Ipo.all
  end

  def new
    @deal = Deal.new
  end

  def create
    @deal = Deal.new(deal_params)
    if @deal.save!
      redirect_to deals_path
    else
      render :new
    end
  end

  def show
    @deal = Deal.find(params[:id])
  end

  def edit
    @deal = Deal.find(params[:id])
  end

  def update
    @deal = Deal.find(params[:id])
    if @deal.update(deal_params)
      redirect_to deal_path(@deal)
    else
      render :edit
    end
  end

  def destroy
    @deal = Deal.find(params[:id])
    @deal.destroy
    redirect_to deals_path
  end

  private

  def deal_params
    params.require(:deal).permit(:date, :premium, :payment_method, :valuation_multiple, :acquirer_id, :target_id, :pdf, :press_release, :payment_method, :valuation_type, :deal_value, :deal_currency, :comments, :bump, :private, :rumors, :offer_price, :ratio_shares)
  end
end

app/controllers/ipos_controller.rb
class IposController < ApplicationController
  def index
    @ipos = Ipo.all
  end

  def new
    @ipo = Ipo.new
  end

  def create
    @ipo = Ipo.new(ipo_params)
    if @ipo.save!
      redirect_to ipos_path
    else
      render :new
    end
  end

  def show
    @ipo = Ipo.find(params[:id])
  end

  def edit
    @ipo = Ipo.find(params[:id])
  end

  def update
    @ipo = Ipo.find(params[:id])
    if @ipo.update(ipo_params)
      redirect_to ipos_path
    else
      render :edit
    end
  end

  def destroy
    @ipo = Ipo.find(params[:id])
    @ipo.destroy
    redirect_to ipos_path
  end

  private

  def ipo_params
    params.require(:ipo).permit(:date, :name, :sector, :lead_underwriter, :valuation, :ipo_logo, :pdf_prospectus)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @comments = Comment.all.order("date DESC")
    @dailyft = daily_articles
  end

  def daily_articles
    tab = Array.new
    Article.where("date = ?", Date.current).each  { |val| tab.push([val.title, val.url, stock_name(val.stock_id)]) }
    return tab
  end

  def stock_name(id)
    return Stock.find(id).name
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all.order("date ASC")
  end

  def new
    @deal = Deal.find(params[:deal_id])
    @post = Post.new
  end

  def show
    @post = Post.find(params[:id])
  end

  def create
    @deal = Deal.find(params[:deal_id])
    @post = Post.new(post_params)
    @post.deal = @deal
    if @post.save!
      redirect_to deal_path(@deal)
    else
      render :new
    end
  end

  def edit
    @deal = Deal.find(params[:deal_id])
    @post = Post.find(params[:id])
  end

  def update
    @deal = Deal.find(params[:deal_id])
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to deal_path(@deal)
    else
      render :edit
    end
  end

  def destroy
    @deal = Deal.find(params[:deal_id])
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to deal_path(@deal)
  end

  private

  def post_params
    params.require(:post).permit(:date, :category, :content, :deal_id)
  end
end

app/controllers/rounds_controller.rb
class RoundsController < ApplicationController
  def index
  end

  def show
  end

  def create
  end

  def new
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/deals/edit.html.erb
<h1>Update this deal</h1>

<div class="container">
  <div class="row">
    <div class="col-6">
      <%= simple_form_for @deal do |f| %>
        <%= f.input :date, as: :string %>
        <%= f.association :target, input_html: { class: "beautiful-dropdown" }, include_hidden: false %>
        <%= f.association :acquirer, input_html: { class: "beautiful-dropdown" }, include_hidden: false %>
        <%= f.input :deal_value %>
        <%= f.input :deal_currency %>
        <%= f.input :premium %>
        <%= f.input :valuation_multiple,input_html: { class: "form-group" } %>
        <%= f.input :valuation_type %>
        <%= f.input :payment_method %>
      </div>
    <div class="col-4">
        <%= f.input :offer_price %>
        <%= f.input :ratio_shares %>
        <%= f.input :bump %>
        <%= f.input :private %>
        <%= f.input :rumors %>
        <%= f.input :comments %>
        <%= f.input :pdf, as: :file, input_html: { class: "btn btn-outline-primary" } %>
        <%= f.input :press_release, as: :file, input_html: { class: "btn btn-outline-primary" } %>
        <%= f.submit "Update", class: "btn btn-primary" %>
      <% end %>
    </div>
    <%= link_to "Back to Deal", deal_path(@deal)  %>
  </div>
</div>

app/views/deals/index.html.erb
<% if current_user.admin %>
  <div class="deal-index-admin">
    <a href="deals/new"><button class="button type1">New Deal</button></a>
    <a href="acquirers/new"><button class="button type2">New Acquirer</button></a>
    <a href="targets/new"><button class="button type3">New Target</button></a>
  </div>
<% end %>

<div class="deal-index-container">
  <ul class="deal-index-table">
    <li class="deal-index-table-header">
      <div class="col-nb-1">Target</div>
      <div class="col-nb-2">Date</div>
      <div class="col-nb-3">Deal</div>
      <div class="col-nb-4">Value</div>
      <div class="col-nb-5">Multiple</div>
      <div class="col-nb-6">Offer Price</div>
      <div class="col-nb-7">Share</div>
      <div class="col-nb-8">vs Mkt Cap</div>
    </li>

    <% @deals.each do |deal| %>
      <li class="deal-index-row">
        <%= link_to "", deal_path(deal), class: "deal-index-a" %>
        <div class="col-nb-1"><%= cl_image_tag deal.target.target_logo.key, width: 100, height: 100, crop: :pad if deal.target.target_logo.attached? %></div>
        <div class="col-nb-2 font-size"><%= deal.date.strftime("%d/%m/%y") %></div>
        <div class="col-nb-3"><%= deal.acquirer.name %> takeover of <%= deal.target.name %></div>
        <div class="col-nb-4 font-size"><%= number_with_delimiter(deal.deal_value, delimiter: ",") %> m<%= deal.deal_currency %></div>
        <div class="col-nb-5 font-size"><%= deal.valuation_multiple %>x <%= deal.valuation_type %></div>
        <% if  deal.offer_price%>
          <div class="col-nb-6 font-size"><%= deal.offer_price %> <%= deal.deal_currency %></div>
        <% else %>
          <div class="col-nb-6 font-size">--</div>
        <% end %>
        <% if deal.ratio_shares%>
          <div class="col-nb-7 font-size"><%= deal.ratio_shares %> <%= deal.acquirer.identifier %></div>
        <% else %>
          <div class="col-nb-7 font-size">--</div>
        <% end %>
     
      </li>
    <% end %>
  </ul>
</div>

app/views/deals/new.html.erb
<h1>Create a new deal</h1>

<div class="container">
  <div class="row">
    <div class="col-6">
      <%= simple_form_for @deal do |f| %>
        <%= f.input :date, as: :string %>
        <%= f.association :target, input_html: { class: "beautiful-dropdown" }, include_hidden: false %>
        <%= f.association :acquirer, input_html: { class: "beautiful-dropdown" }, include_hidden: false %>
        <%= f.input :deal_value %>
        <%= f.input :deal_currency %>
        <%= f.input :premium %>
        <%= f.input :valuation_multiple,input_html: { class: "form-group" } %>
        <%= f.input :valuation_type %>
        <%= f.input :payment_method %>
      </div>
    <div class="col-4">
        <%= f.input :offer_price %>
        <%= f.input :ratio_shares %>
        <%= f.input :bump %>
        <%= f.input :private %>
        <%= f.input :rumors %>
        <%= f.input :comments %>
        <%= f.input :pdf, as: :file, input_html: { class: "btn btn-outline-primary" } %>
        <%= f.input :press_release, as: :file, input_html: { class: "btn btn-outline-primary" } %>
        <%= f.submit "Create", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/deals/show.html.erb
<div class="container">
      <div class="row col-6 justify-items-center mt-3 mb-1">
        <%= cl_image_tag @deal.acquirer.acquirer_logo.key, width: 150, height: 150, crop: :pad if @deal.acquirer.acquirer_logo.attached? %>
        <%= cl_image_tag @deal.target.target_logo.key, width: 150, height: 150, crop: :pad if @deal.target.target_logo.attached? %>
      </div>

        <div class="row mt-1">
          <div class="col-10 mb-3">
            <h2><%= @deal.target.name %> takeover by <%= @deal.acquirer.name %></h2>
            <div class="row col-8 mt-3 mb-3 text-center">
              <%= link_to "Deal presentation", @deal.pdf, class: "btn btn-ghost mr-3 ml-3" if @deal.pdf.attached? %>
              <%= link_to "Deal press release", @deal.press_release, class: "btn btn-ghost mr-3 ml-3" if @deal.press_release.attached? %>
            </div>
              <p><%= @deal.date.strftime("%d/%m/%y") %>, <%= @deal.premium %>% premium, <%= @deal.valuation_multiple %>x <%= @deal.valuation_type %></p>
              <p><%= @deal.offer_price %> <%= @deal.deal_currency %> with a <%= @deal.payment_method %></p>
              <p class="text-justify"><%= @deal.comments %></p>
              <button type="button" class="btn btn-ghost mr-3 ml-3" data-toggle="modal" data-target="#exampleModal">Create a Post</button>
              <%= link_to "Back to Deals", deals_path, class: "btn btn-ghost mr-3 ml-3" %>
              <%= link_to "Update this deal", edit_deal_path(@deal), class: "btn btn-ghost mr-3 ml-3" %>
          </div>
        </div>


    <!--Accordion wrapper-->
    <div class="accordion md-accordion border-top mb-3" id="accordionEx" role="tablist" aria-multiselectable="true">

      <!-- Accordion card -->
      <div class="card">

        <!-- Card header -->
        <div class="card-header" role="tab" id="headingOne1">
          <a data-toggle="collapse" data-parent="#accordionEx" href="#collapseOne1" aria-expanded="true"
            aria-controls="collapseOne1">
            <h5 class="btn-success p-3 mb-0">
              Newsflow from Financials time (if any since beginning of the year) <i class="fas fa-angle-down rotate-icon float-right"></i>
            </h5>
          </a>
        </div>

        <!-- Card body -->
        <div id="collapseOne1" class="collapse show" role="tabpanel" aria-labelledby="headingOne1"
          data-parent="#accordionEx">
          <div class="card-body">
            <div class="stock_newsflow" data-name="<%= @deal.acquirer.name %>" data-identifier="<%= @deal.acquirer.identifier %>"></div>
          </div>
        </div>
      </div>
    </div>
      <!-- Accordion card -->


    <div class="row mt-3">
        <div class="col-8 align-content-center text-justify mr-2 ml-2 mt-2 mb-2">
            <%= render "posts/index-posts" %>
        </div>
    </div>
  </div>
    <%= render "posts/modal" %>
  </div>

app/views/ipos/create.html.erb
<h1>Ipos#create</h1>
<p>Find me in app/views/ipos/create.html.erb</p>

app/views/ipos/destroy.html.erb
<h1>Ipos#destroy</h1>
<p>Find me in app/views/ipos/destroy.html.erb</p>

app/views/ipos/edit.html.erb
<h1>Edit IPO</h1>

<div class="container">
  <div class="row">
    <div class="col-6">
      <%= simple_form_for @ipo do |f| %>
        <%= f.input :date, as: :string %>
        <%= f.input :name %>
        <%= f.input :sector, collection: ["Aerospace & Defense", "Airlines", "Banks", "Basic Resources","Construction","Energy","Financials","Food & Beverage", "Health", "Healthcare", "Industrials", "Media", "Mining", "Oil & Gas", "Pharmaceuticals","Property", "Retail","Retail & Consumer","Support Services","Technology", "Travel & Leisure"] %>
      </div>
    <div class="col-4">
        <%= f.input :pdf_prospectus, as: :file, input_html: { class: "btn btn-outline-primary" } %>
        <%= f.input :ipo_logo, as: :file, input_html: { class: "btn btn-outline-primary" } %>
        <%= f.submit "update", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/ipos/index.html.erb
<% if current_user.admin %>
<div class="ipos-index-admin">
  <a href="ipos/new"><button class="button type3">New IPOS</button></a>
</div>
<% end %>
 
<div class="ipo-index-container">
  <% @ipos.each_with_index do |ipo| %>
    <div class="card-ipo-index">
      <h2 class = "ipo-index-h2"><%= ipo.name %></h2>
      <i class="ipo-index-i fas fa-arrow-right"></i>
      <p class="p-ipo-index"><%= ipo.sector %></p>
      <img class="pic">
      <ul class="ipo-index-ul">
        <li class="ipo-index-li"></li>
        <li class="ipo-index-li"></li>
        <li class="ipo-index-li"></li>
        <li class="ipo-index-li"></li>
        <li class="ipo-index-li"></li>
        <li class="ipo-index-li"></li>
        <li class="ipo-index-li"></li>
        <li class="ipo-index-li"></li>
        <li class="ipo-index-li"></li>
        <li class="ipo-index-li"></li>
        <li class="ipo-index-li"></li>
        <li class="ipo-index-li"></li>
        <li class="ipo-index-li"></li>
        <li class="ipo-index-li"></li>
        <li class="ipo-index-li"></li>
        <li class="ipo-index-li"></li>
        <li class="ipo-index-li"></li>
        <li class="ipo-index-li"></li>
        <li class="ipo-index-li"></li>
        <li class="ipo-index-li"></li>
        <li class="ipo-index-li"></li>
        <li class="ipo-index-li"></li>
        <li class="ipo-index-li"></li>
      </ul>
      <div class="ipo-timeline">
        <i class="ipo-index-i"><%= ipo.date.strftime("%d / %m / 20%y ") %></i>
        <i class="ipo-index-i far fa-clock"></i>
      </div>
      <button><%= link_to "", ipo.pdf_prospectus, class: "ipo-index-a" %></button>
    </div>  
  <% end %>
</div>
  

    
  

app/views/ipos/new.html.erb
<h1>Create a new IPO</h1>

<div class="container">
  <div class="row">
    <div class="col-6">
      <%= simple_form_for @ipo do |f| %>
        <%= f.input :date, as: :string %>
        <%= f.input :name %>
        <%= f.input :sector, collection: ["Aerospace & Defense", "Airlines", "Banks", "Basic Resources","Construction","Energy","Financials","Food & Beverage", "Health", "Healthcare", "Industrials", "Media", "Mining", "Oil & Gas", "Pharmaceuticals","Property", "Retail","Retail & Consumer","Support Services","Technology", "Travel & Leisure"] %>
      </div>
    <div class="col-4">
        <%= f.input :pdf_prospectus, as: :file, input_html: { class: "btn btn-outline-primary" } %>
        <%= f.input :ipo_logo, as: :file, input_html: { class: "btn btn-outline-primary" } %>
        <%= f.submit "Create", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/ipos/show.html.erb
<h1>Ipos#show</h1>
<p>Find me in app/views/ipos/show.html.erb</p>

app/views/ipos/update.html.erb
<h1>Ipos#update</h1>
<p>Find me in app/views/ipos/update.html.erb</p>

app/views/posts/_form.html.erb
    <div class="container">
        <%= simple_form_for [@deal, Post.new]  do |f| %>
        <%= f.input :date, as: :string %>
        <%= f.association :deal, as: :hidden, input_html: { value: @deal.id } %>
        <%= f.input :category, collection: ["Funding", "Regulation/Antitrust", "Sector overview", "Market reaction", "Valuation", "Shareholders vote", "Earnings", "Deal spread", "Rumors"] %>
        <%= f.input :content, as: :trix_editor %>
        <%= f.submit "Create", class: "btn btn-primary" %>
      <% end %>
    </div>

app/views/posts/_index-posts.html.erb
<div class="posts">
  <% @deal.posts.order("date DESC").each do |post| %>
  <div class="post border-top mt-3">
    <h5 class="mt-2">💥 <%= link_to deal_post_path(@deal, post), method: :delete, data: { confirm: "Are you sure?" } do %><i class="fa fa-trash destroy_dose "></i> <% end %> <%= post.date.strftime("%d/%m/%y") %> - <strong><%= post.category %></strong></h5>
    <p class="text-justify"><%=raw post.content %></p>
    <%= link_to "modify this post", edit_deal_post_path(@deal, post), class: "btn btn-flat w-100 mb-2 mt-2 mr-2 ml-2"  %>
    </div>
  <% end %>
  <%= render "posts/modal" %>
</div>

app/views/posts/_modal.html.erb
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel"><%= @deal.acquirer.name %> / <%= @deal.target.name %></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= render "posts/form" %>
      </div>
    </div>
  </div>
</div>

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/destroy.html.erb
<h1>Posts#destroy</h1>
<p>Find me in app/views/posts/destroy.html.erb</p>

app/views/posts/edit.html.erb
    <div class="container">
        <%= simple_form_for [@deal, @post]  do |f| %>
        <%= f.input :date, as: :string %>
        <%= f.association :deal, as: :hidden, input_html: { value: @deal.id } %>
        <%= f.input :category, collection: ["Funding", "Regulation/Antitrust", "Sector overview", "Market reaction", "Valuation", "Shareholders vote", "Earnings", "Deal spread", "Rumors"] %>
        <%= f.input :content, as: :trix_editor %>
        <%= f.submit "Update", class: "btn btn-primary" %>
      <% end %>
    </div>

app/views/posts/index.html.erb
<% @deal.posts.each do |post| %>
p>💥 <%= link_to post_path(post), method: :delete, data: { confirm: "Are you sure?" } do %><i class="fa fa-trash destroy_dose "></i> <% end %> <%= post.date.strftime("%d/%m/%y") %> - <%= post.content %> - <strong><%= post.category %></strong></p>
<% end %>

app/views/posts/new.html.erb
<h1>Create a new post</h1>

    <div class="container">
        <%= simple_form_for [@deal, @post]  do |f| %>
        <%= f.input :date, as: :string %>
        <%= f.association :deal, as: :hidden, input_html: { value: @deal.id } %>
        <%= f.input :category, collection: ["Funding", "Regulation/Antitrust", "Sector overview", "Market reaction", "Valuation", "Shareholders vote", "Earnings", "Deal spread", "Runmors"] %>
        <%= f.input :content %>
        <%= f.submit "Create", class: "btn btn-primary" %>
      <% end %>
    </div>

app/views/posts/show.html.erb
<div class="container">
      <div class="row col-6 justify-items-center mt-3 mb-3">
        <%= cl_image_tag @deal.acquirer.acquirer_logo.key, width: 150, height: 150, crop: :pad if @deal.acquirer.acquirer_logo.attached? %>
        <%= cl_image_tag @deal.target.target_logo.key, width: 150, height: 150, crop: :pad if @deal.target.target_logo.attached? %>
      </div>

      <div class="row col-8 mt-3">
        <%= link_to "Deal presentation", @deal.pdf, class: "btn btn-ghost mr-3 ml-3" if @deal.pdf.attached? %>
        <%= link_to "Deal press release", @deal.press_release, class: "btn btn-ghost mr-3 ml-3" if @deal.press_release.attached? %>
      </div>


        <div class="row mt-3">
          <div class="col-10">
            <h2><%= @deal.target.name %> takeover by <%= @deal.acquirer.name %></h2>
              <p>Deal premium: <%= @deal.premium %>%</p>
              <p>Valuation: <%= @deal.valuation_multiple %>x <%= @deal.valuation_type %></p>
              <p class="text-justify"><%= @deal.comments %></p>
              <%= link_to "Create a Post", new_deal_post_path(@deal), class: "btn btn-ghost mr-3 ml-3"  %>
              <%= link_to "Back to Deals", deals_path, class: "btn btn-ghost mr-3 ml-3" %>
              <%= link_to "Update this deal", edit_deal_path(@deal), class: "btn btn-ghost mr-3 ml-3" %>
          </div>
        </div>

        <div class="row mt-3">
          <div class="col-10">
            <% @posts.each do |post| %>
            <%= post.date %>
            <%= post.content %>
            <%= post.category %>
            <% end %>
          </div>
        </div>
  </div>

app/views/posts/update.html.erb
<h1>Posts#update</h1>
<p>Find me in app/views/posts/update.html.erb</p>